### PR TITLE
Fix the project finder geographic filter. Closes #1030

### LINKED ISSUE #1030: project finder filter by map is not working
The following is not working. 
* filter by region -> project does not get updated
* refresh the page after selecting filter region throws the whole page to display nothing

### PR DESCRIPTION
**Pull request by cofiem**
Restore the filter from querystring.
Check the geoSearch when map is initialised, as geoSearch may be set before.
Added console logging to assist with debugging.

### CODE REVIEW

File: grails-app/assets/javascripts/project-finder.js [hunk 1]
```diff
@@ -202,6 +205,7 @@ function ProjectFinder(config) {
     }
 
     function initialiseMap() {
+        console.log('Initialising geographic filter map. Is map already initialised? ', mapInitialised);
```
Comment (nickdos) [inline grails-app/assets/javascripts/project-finder.js:208]: Did you mean to keep this console logging in PR?

File: grails-app/assets/javascripts/project-finder.js [hunk 2]
```diff
@@ -211,6 +215,11 @@ function ProjectFinder(config) {
 
             var regionSelector = Biocollect.MapUtilities.createKnownShapeMapControl(spatialFilter, fcConfig.featuresService, fcConfig.regionListUrl);
             spatialFilter.addControl(regionSelector);
+
+            // geoSearch may have been set before map was initialised
+            console.log('Updating filter with value that may have been set before initialisation: ', geoSearch);
```
Comment (nickdos) [inline grails-app/assets/javascripts/project-finder.js:220]: ditto

**Comment by temi** [comment]
Most of the drawn shapes are working except for marker / point. Selecting a point does not seems to refresh projects. It also does not draw the point on map after refresh.
